spring:
  application:
    name: AutoPartsStore

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true