spring:
  application:
    name: AutoPartsStore

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/autoparts_store
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true