CREATE TABLE manufacturer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    country VARCHAR(100),
    website VARCHAR(255)
);


CREATE TABLE part_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500)
);


CREATE TABLE part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    sku VARCHAR(50) NOT NULL UNIQUE,

    article VARCHAR(100) NOT NULL,

    description VARCHAR(1000),

    price NUMERIC(12, 2) NOT NULL,

    manufacturer_id BIGINT NOT NULL,

    category_id BIGINT NOT NULL,

    CONSTRAINT chk_part_price
      CHECK (price >= 0),

    CONSTRAINT fk_part_manufacturer
      FOREIGN KEY (manufacturer_id)
          REFERENCES manufacturer(id),

    CONSTRAINT fk_part_category
      FOREIGN KEY (category_id)
          REFERENCES part_category(id)
);