CREATE TABLE stock (
                       part_id BIGINT PRIMARY KEY,
                       quantity INTEGER NOT NULL DEFAULT 0,

                       CONSTRAINT fk_stock_part
                           FOREIGN KEY (part_id)
                               REFERENCES part(id),

                       CONSTRAINT chk_stock_quantity
                           CHECK (quantity >= 0)
);


CREATE TABLE inventory_movement (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                    part_id BIGINT NOT NULL,

                                    type VARCHAR(30) NOT NULL,

                                    quantity INTEGER NOT NULL,

                                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                    comment VARCHAR(500),

                                    CONSTRAINT fk_inventory_movement_part
                                        FOREIGN KEY (part_id)
                                            REFERENCES part(id),

                                    CONSTRAINT chk_inventory_movement_quantity
                                        CHECK (quantity > 0)
);