CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        customer_id BIGINT NOT NULL,

                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        status VARCHAR(30) NOT NULL,

                        total_price NUMERIC(12, 2) NOT NULL DEFAULT 0,

                        CONSTRAINT fk_orders_customer
                            FOREIGN KEY (customer_id)
                                REFERENCES customer(id),

                        CONSTRAINT chk_orders_total_price
                            CHECK (total_price >= 0)
);


CREATE TABLE order_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            order_id BIGINT NOT NULL,
                            part_id BIGINT NOT NULL,

                            quantity INTEGER NOT NULL,

                            unit_price NUMERIC(12, 2) NOT NULL,

                            CONSTRAINT fk_order_item_order
                                FOREIGN KEY (order_id)
                                    REFERENCES orders(id),

                            CONSTRAINT fk_order_item_part
                                FOREIGN KEY (part_id)
                                    REFERENCES part(id),

                            CONSTRAINT chk_order_item_quantity
                                CHECK (quantity > 0),

                            CONSTRAINT chk_order_item_price
                                CHECK (unit_price >= 0)
);


ALTER TABLE inventory_movement
    ADD COLUMN order_id BIGINT;


ALTER TABLE inventory_movement
    ADD CONSTRAINT fk_inventory_movement_order
        FOREIGN KEY (order_id)
            REFERENCES orders(id);