CREATE TABLE IF NOT EXISTS vehicle_application (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     make VARCHAR(100) NOT NULL,
                                     model VARCHAR(100) NOT NULL,
                                     generation VARCHAR(100),

                                     year_from INTEGER NOT NULL,
                                     year_to INTEGER,

                                     engine_code VARCHAR(50),
                                     engine_volume NUMERIC(4, 1),
                                     power INTEGER,

                                     fuel_type VARCHAR(30),
                                     transmission VARCHAR(30),
                                     drive_type VARCHAR(30),
                                     body_type VARCHAR(30),

                                     CONSTRAINT chk_vehicle_application_years
                                         CHECK (
                                             year_from >= 1900
                                                 AND (year_to IS NULL OR year_to >= year_from)
                                             )
);


CREATE TABLE IF NOT EXISTS part_fitment (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              part_id BIGINT NOT NULL,
                              vehicle_application_id BIGINT NOT NULL,

                              CONSTRAINT fk_part_fitment_part
                                  FOREIGN KEY (part_id)
                                      REFERENCES part(id)
                                      ON DELETE CASCADE,

                              CONSTRAINT fk_part_fitment_vehicle
                                  FOREIGN KEY (vehicle_application_id)
                                      REFERENCES vehicle_application(id)
                                      ON DELETE CASCADE,

                              CONSTRAINT uq_part_fitment
                                  UNIQUE (part_id, vehicle_application_id)
);