CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          email VARCHAR(255) NOT NULL UNIQUE,
                          password_hash VARCHAR(255) NOT NULL,

                          role VARCHAR(20) NOT NULL,

                          customer_id BIGINT UNIQUE,

                          CONSTRAINT fk_app_user_customer
                              FOREIGN KEY (customer_id)
                                  REFERENCES customer(id)
);